# Generated by Django 6.0.4 on 2026-05-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fever', 'Fever'), ('Cold & Cough', 'Cold & Cough'), ('Stomach', 'Stomach'), ('Pain Relief', 'Pain Relief'), ('Vitamins', 'Vitamins'), ('Antibiotics', 'Antibiotics'), ('Skin Care', 'Skin Care'), ('General', 'General')], max_length=50)),
                ('price', models.IntegerField(default=50)),
                ('description', models.TextField()),
                ('dosage', models.CharField(default='As directed by physician', max_length=200)),
                ('stock', models.IntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_address', models.TextField()),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
